### ISSUE TITLE
NPE if Handle.readJsonFileFromBuildArchive is called

### ISSUE THREAD

**Issue by alxsap** [sap-production/parameterized-remote-trigger-plugin#17]
The current version 5bb7a1a4565e4e8a0d3c3adef52e4f94772228c1 fails if Handle.readJsonFileFromBuildArchive is called:
```
java.lang.NullPointerException
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.getAuthorizedConnection(RemoteBuildConfiguration.java:1219)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.sendHTTPCall(RemoteBuildConfiguration.java:1043)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.sendHTTPCall(RemoteBuildConfiguration.java:937)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.pipeline.Handle.readJsonFileFromBuildArchive(Handle.java:378)
```

Example:
```
node {
    stage("Test") {
        def handle = triggerRemoteJob job: 'https://host:1234/job/RemoteJob'
        def results = handle.readJsonFileFromBuildArchive('build-results.json')
        echo results.x
    }
}
```
the *RemoteJob* needs to write and archive a build-results.json file with `{"x":"y"}`.

## Analysis
The problem was caused by removing effectiveRemoteServer from RemoteBuildConfiguration and moving it into the Context.
https://github.com/sap-production/parameterized-remote-trigger-plugin/blob/ce6a1d88af50c3324a14bc0d82b86364999ec917/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java#L110

As you can see here Handle creates a new Context (with effectiveRemoteServer null).
https://github.com/sap-production/parameterized-remote-trigger-plugin/blob/ce6a1d88af50c3324a14bc0d82b86364999ec917/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/Handle.java#L381

getAuthorizedConnection before accessed effectiveRemoteServer directly without Context...
https://github.com/sap-production/parameterized-remote-trigger-plugin/blob/ce6a1d88af50c3324a14bc0d82b86364999ec917/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java#L1211

...now it does:
https://github.com/sap-production/parameterized-remote-trigger-plugin/blob/5bb7a1a4565e4e8a0d3c3adef52e4f94772228c1/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java#L1219

<div id="architecture"></div>

### Architectural issue
The triggerRemoteBuild command returns a handle. Using this Handle further operations are possible, like readJsonFileFromBuildArchive. This handle does currently not contain the effectiveRemoteServer information which is required.

Previously this information was taken from the remoteBuildConfig object. Now it is in the BuildContext and the Handle does not contain the full context, but only serializable important data.

💡 All relevant information for effectiveRemoteServer should also be stored in the Handle and when creating a new BuildContext (see below) the effectiveRemoteServer object should be restored based on this data. (Check if effectiveRemoteServer is maybe serializable and could be added as whole?)

## Other likely issues caused by this
Check the call hierarchy to the constructors of `BuildContext`

- ✅ org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.perform(Run<?, ?>, FilePath, Launcher, TaskListener)
- ✅ org.jenkinsci.plugins.ParameterizedRemoteTrigger.pipeline.RemoteBuildPipelineStep.Execution.run()
- ❌ org.jenkinsci.plugins.ParameterizedRemoteTrigger.pipeline.Handle.getBuildData(String, PrintStream)
- ❌ org.jenkinsci.plugins.ParameterizedRemoteTrigger.pipeline.Handle.getBuildStatus(boolean)
- ❌ org.jenkinsci.plugins.ParameterizedRemoteTrigger.pipeline.Handle.readJsonFileFromBuildArchive(String)

The first two are OK, here `remoteBuildConfig.performTriggerAndGetQueueId(context)` is called which sets the `effectiveRemoteServer`.

For the others `performTriggerAndGetQueueId` has already been called and they continue with a new instance of `BuildContext` -> the `effectiveRemoteServer` is lost and null in the new `BuildContext`.
Before the changes `effectiveRemoteServer` was set on the `remoteBuildConfig` and still available.

:warning: Moving `effectiveRemoteServer` simply back *might* also not not be an option because we did this change due to parallelization of builds, afaik.

**Comment by alxsap** [comment]
The problem was caused by removing effectiveRemoteServer from RemoteBuildConfiguration and moving it into the Context.
https://github.com/sap-production/parameterized-remote-trigger-plugin/blob/ce6a1d88af50c3324a14bc0d82b86364999ec917/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java#L110

As you can see here Handle creates a new Context (with effectiveRemoteServer null).
https://github.com/sap-production/parameterized-remote-trigger-plugin/blob/ce6a1d88af50c3324a14bc0d82b86364999ec917/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/Handle.java#L381

getAuthorizedConnection before accessed effectiveRemoteServer directly without Context...
https://github.com/sap-production/parameterized-remote-trigger-plugin/blob/ce6a1d88af50c3324a14bc0d82b86364999ec917/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java#L1211

...now it does:
https://github.com/sap-production/parameterized-remote-trigger-plugin/blob/5bb7a1a4565e4e8a0d3c3adef52e4f94772228c1/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java#L1219
